export const employees = [
  {
    id: "EMP-7BFA5C2B",
    name: "Rendy",
    department: "Production",
    position: "Operator",
    rfidUid: "16210C07",
    pin: "••••••",
    activeTransactions: 1,
    status: "ACTIVE",
    lastActivity: "2 min ago",
    joinedDate: "12 Jan 2026",
  },
  {
    id: "EMP-4A91C8D3",
    name: "Andi Pratama",
    department: "Maintenance",
    position: "Technician",
    rfidUid: "A83F21D9",
    pin: "••••••",
    activeTransactions: 0,
    status: "ACTIVE",
    lastActivity: "18 min ago",
    joinedDate: "08 Jan 2026",
  },
  {
    id: "EMP-9C42E7F1",
    name: "Dimas",
    department: "Production",
    position: "Supervisor",
    rfidUid: "B71C09E4",
    pin: "••••••",
    activeTransactions: 2,
    status: "ACTIVE",
    lastActivity: "5 min ago",
    joinedDate: "20 Dec 2025",
  },
  {
    id: "EMP-2D8A61B4",
    name: "Fajar",
    department: "Engineering",
    position: "Engineer",
    rfidUid: "C912F03A",
    pin: "••••••",
    activeTransactions: 0,
    status: "INACTIVE",
    lastActivity: "3 days ago",
    joinedDate: "14 Nov 2025",
  },
  {
    id: "EMP-6E31A9C5",
    name: "Rizky",
    department: "Maintenance",
    position: "Technician",
    rfidUid: "E4517BC2",
    pin: "••••••",
    activeTransactions: 1,
    status: "ACTIVE",
    lastActivity: "12 min ago",
    joinedDate: "03 Feb 2026",
  },
];

export const getEmployeeById = (id) => {
  return employees.find((employee) => employee.id === id);
};