export const TOOLS = [
  {
    id: "TOOL-280F7D0F",
    assetNumber: "AST-001",
    name: "Impact Driver",
    category: "Power Tool",
    cabinetId: "CAB-DF11099F",
    cabinetLabel: "CAB-001",
    slotNumber: 1,
    status: "AVAILABLE",
    condition: "GOOD",
    usageCount: 142,
    maintenanceThreshold: 200,
    lastUsed: "Today, 09:42",
    lastReturned: "Today, 10:03",
  },

  {
    id: "TOOL-118A2C41",
    assetNumber: "AST-002",
    name: "Hammer",
    category: "Hand Tool",
    cabinetId: "CAB-DF11099F",
    cabinetLabel: "CAB-001",
    slotNumber: 2,
    status: "AVAILABLE",
    condition: "GOOD",
    usageCount: 87,
    maintenanceThreshold: 200,
    lastUsed: "Yesterday, 14:20",
    lastReturned: "Yesterday, 14:42",
  },

  {
    id: "TOOL-9E30B7D2",
    assetNumber: "AST-003",
    name: "Multimeter",
    category: "Measuring Tool",
    cabinetId: "CAB-DF11099F",
    cabinetLabel: "CAB-001",
    slotNumber: 3,
    status: "IN_USE",
    condition: "GOOD",
    usageCount: 64,
    maintenanceThreshold: 150,
    lastUsed: "Today, 10:15",
    lastReturned: null,
  },

  {
    id: "TOOL-4C7712AA",
    assetNumber: "AST-004",
    name: "Adjustable Wrench",
    category: "Hand Tool",
    cabinetId: "CAB-DF11099F",
    cabinetLabel: "CAB-001",
    slotNumber: 4,
    status: "AVAILABLE",
    condition: "GOOD",
    usageCount: 112,
    maintenanceThreshold: 200,
    lastUsed: "Today, 08:12",
    lastReturned: "Today, 08:34",
  },

  {
    id: "TOOL-5591D0F3",
    assetNumber: "AST-005",
    name: "Pliers",
    category: "Hand Tool",
    cabinetId: "CAB-DF11099F",
    cabinetLabel: "CAB-001",
    slotNumber: 5,
    status: "MAINTENANCE",
    condition: "MAINTENANCE_REQUIRED",
    usageCount: 196,
    maintenanceThreshold: 200,
    lastUsed: "Today, 07:45",
    lastReturned: "Today, 08:02",
  },

  {
    id: "TOOL-A22F60E9",
    assetNumber: "AST-006",
    name: "Drill",
    category: "Power Tool",
    cabinetId: "CAB-002",
    cabinetLabel: "CAB-002",
    slotNumber: 4,
    status: "AVAILABLE",
    condition: "GOOD",
    usageCount: 53,
    maintenanceThreshold: 200,
    lastUsed: "Yesterday, 16:10",
    lastReturned: "Yesterday, 16:35",
  },

  {
    id: "TOOL-002001",
    assetNumber: "AST-007",
    name: "Torque Wrench",
    category: "Hand Tool",
    cabinetId: "CAB-002",
    cabinetLabel: "CAB-002",
    slotNumber: 1,
    status: "AVAILABLE",
    condition: "GOOD",
    usageCount: 74,
    maintenanceThreshold: 200,
    lastUsed: "Today, 08:30",
    lastReturned: "Today, 08:48",
  },

  {
    id: "TOOL-004001",
    assetNumber: "AST-008",
    name: "Impact Driver",
    category: "Power Tool",
    cabinetId: "CAB-004",
    cabinetLabel: "CAB-004",
    slotNumber: 1,
    status: "IN_USE",
    condition: "GOOD",
    usageCount: 178,
    maintenanceThreshold: 200,
    lastUsed: "Today, 10:22",
    lastReturned: null,
  },
];

export function getToolById(id) {
  return TOOLS.find(
    (tool) => tool.id === id
  );
}